### ISSUE TITLE
Clan tag bug

### ISSUE THREAD

**Issue by tirziz** [danielkrupinski/Osiris#368] opened 2019-07-25 10:07 UTC
It is not showing origin my clan tag even I dont use clan tag changer,

**Comment by Bywnb** [comment] 2019-07-25 11:07
i think its not a bug

**Comment by NexSqaud** [comment] 2019-07-25 11:20
I think this will fix this problem:
In misc.h
```c++
constexpr void setClanTag(const char* clanTag) noexcept
{
    if (strlen(clanTag) != 0) 
    { 
        memory.setClanTag(clanTag, clanTag); 
    }
}
```

**Comment by tirziz** [comment] 2019-07-25 12:53
And this function keep update clan tag like every tick, It might be dangerous if u play in community servers

**Comment by danielkrupinski** [comment] 2019-07-25 16:40
> And this function keep update clan tag like every tick, It might be dangerous if u play in community servers

It updates clan tag every 0.6 s.

**Comment by danielkrupinski** [comment] 2019-07-25 17:10
Should be fixed now.

**Closed by danielkrupinski** 2019-07-25 17:10 UTC
