### ISSUE TITLE
[SUGGESTION] Bypass sv_pure

### ISSUE THREAD

**Issue by Oly-UK** [danielkrupinski/Osiris#687] opened 2019-10-20 15:47 UTC
Hey, i would love to see a bypass for sv_pure, to have some nostalgia on the old gun sounds. What do you guys think?

**Comment by AbdallahMehiz** [comment] 2019-10-20 16:00
#569 it has been already thought of
soo... why don't you paste it from another cheat your self/code it youself

**Comment by anonymouschicken111** [comment] 2019-10-20 17:56
First of all add ur own SendNetMsg hook

**Comment by hyperxpro** [comment] 2019-10-20 18:51
Duplicate of https://github.com/danielkrupinski/Osiris/issues/569

**Closed** 2023-10-04 18:18 UTC
