### ISSUE TITLE
new update?

### ISSUE THREAD

**Issue by dzgzxje** [danielkrupinski/Osiris#775] opened 2019-11-19 17:05 UTC
is it still working for new update guys? if it is then will i get higher chance of getting ban while using this ?

**Comment by thomas0aotian** [comment] 2019-11-19 17:54
Duplicate of 772 and no

**Comment by 0xE232FE** [comment] 2019-11-19 18:35
fix: https://github.com/danielkrupinski/Osiris/pull/698

**Closed** 2019-11-19 21:38 UTC
