### ISSUE TITLE
chams issue since update 25.02.20

### ISSUE THREAD

**Issue by steel4me** [danielkrupinski/Osiris#1154] opened 2020-02-25 20:47 UTC
just for info. had a strange thing, one of my five teammates had no chams. i forgot to save screenshot. never had this before, maybe it has something to do with update, also i had strange freezes.

trying to find out more, can someone doublecheck or confirm?

**Comment by steel4me** [comment] 2020-02-25 23:29
y, seems to be update ;)

**Comment by steel4me** [comment] 2020-02-26 09:18
Ok...thought i can find it easy but with local bot game it doesnt occur

![image](https://user-images.githubusercontent.com/26707054/75330406-521ed800-5881-11ea-9fac-474dd5624dea.png)

**Comment by xAkiraMiura** [comment] 2020-02-26 11:48
custom player models have a different name and are not picked up by chams.
https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hacks/Chams.cpp#L47
modify it to include the new names.

**Comment by steel4me** [comment] 2020-02-26 12:23
> custom player models have a different name and are not picked up by chams.
> https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hacks/Chams.cpp#L47
> modify it to include the new names.

makes sense. thank you. i will have a look, any experience about freezes or laggs snce update from yesterday?

**Comment by Evilhelder** [comment] 2020-02-27 00:45
stil crashing... D:

**Comment by tamas0313** [comment] 2020-02-27 08:28
where to find custom models names?

**Comment by steel4me** [comment] 2020-02-27 09:20
> stil crashing... D:

i have no crashes! everything works fine expect some strange mini laggs / freezes since update and missing custom model names for chams. they just dont draw, a**gain, no crash till now!**

**Comment by steel4me** [comment] 2020-02-27 10:24
> where to find custom models names?

As far as i know:

For CTs
Local CT (SAS) : ctm_sas
B Squadron Officer: ctm_sas_variantf
Special agent Ava: ctm_fbi_variantb
FBI operator: ctm_fbi_variantf
Markus Delrow: ctm_fbi_variantg
Michael Syfers: ctm_fbi_varianth
SEAL Team 6 Soldier: ctm_st6_variante
Buckshot: ctm_st6_variantg
Lt. Commander Ricksaw: ctm_st6_varianti
3rd Commando Company: ctm_st6_variantk
'Two Times' McCoy: ctm_st6_variantm

For Ts
The Elite Mr. Muhlik: tm_leet_variantf
Ground Rebel: tm_leet_variantg
Osiris: tm_leet_varianth
Prof. Shahmat: tm_leet_varianti
Local T (Phoenix): tm_phoenix
Enforcer: tm_phoenix_variantf
Slingshot: tm_phoenix_variantg
Soldier: tm_phoenix_varianth
Dragomir: tm_balkan_variantf
Rezan The Ready: tm_balkan_variantg
'The Doctor' Romanov: tm_balkan_varianth
Maximus: tm_balkan_varianti
Blackwolf: tm_balkan_variantj


But this is only used with for Visuals.cpp with getModel and, as far as i understand, has nothing to do with  `if (std::strstr(info.model->name, "models/player"))`

@xAkiraMiura so, i have to take my statement back, it doesn't make sense...in matchmaking every model should begin with "models/player" and chams should draw, this is ugly to debug

**Comment by xAkiraMiura** [comment] 2020-02-27 11:53
bot's don't have custom models. you have to try it with a friend that has a custom model.

**Comment by steel4me** [comment] 2020-02-27 15:26
> bot's don't have custom models. you have to try it with a friend that has a custom model.

done. i took one account with osiris in debug mode and another with AVG sandbox. Joined both accounts to same server, with second account i took same CT model from screenshot (Buckshot: ctm_st6_variantg) and chams rendering / drawing was correct, output was `...models/player/custom_player/legacy/ctm_st6_variantg.mdl` ...something strange is going on. Did some offsets / signatures change? Are some Entitys wrong?

**Comment by tamas0313** [comment] 2020-02-27 16:23
bool Chams::render(void* ctx, void* state, const ModelRenderInfo& info, matrix3x4* customBoneToWorld) const noexcept
{
	if (std::strstr(info.model->name, "models/player"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/ctm_sas.mdl"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/ctm_sas_variantf.mdl"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/ctm_fbi_variantb.mdl"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/ctm_fbi_variantf.mdl"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/ctm_fbi_variantg.mdl"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/ctm_fbi_varianth.mdl"))	
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/ctm_st6_variantg.mdl"))	
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/ctm_st6_variante.mdl"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/ctm_st6_varianti.mdl"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/ctm_st6_variantk.mdl"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/ctm_st6_variantm.mdl"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/tm_leet_variantf.mdl"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/tm_leet_variantg.mdl"))	
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/tm_leet_varianth.mdl"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/tm_leet_varianti.mdl"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/tm_phoenix.mdl"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/tm_phoenix_variantf.mdl"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/tm_phoenix_variantg.mdl"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/tm_phoenix_varianth.mdl"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/tm_balkan_variantf.mdl"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/tm_balkan_variantg.mdl"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/tm_balkan_varianth.mdl"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/tm_balkan_varianti.mdl"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	if (std::strstr(info.model->name, "models/player/custom_player/legacy/tm_balkan_variantj.mdl"))
		return renderPlayers(ctx, state, info, customBoneToWorld);
	else if (std::strstr(info.model->name, "sleeve"))
		renderSleeves(ctx, state, info, customBoneToWorld);
	else if (std::strstr(info.model->name, "arms"))
		renderHands(ctx, state, info, customBoneToWorld);
	else if (std::strstr(info.model->name, "models/weapons/v_")
		&& !std::strstr(info.model->name, "tablet")
		&& !std::strstr(info.model->name, "parachute")
		&& !std::strstr(info.model->name, "fists"))
		renderWeapons(ctx, state, info, customBoneToWorld);

	return true;
}


for me working!

**Comment by steel4me** [comment] 2020-02-27 17:32
you don't have to do that...interpret it for yourself as "if string contains"... "models/player" inlcudes all your if statements.

**Comment by xAkiraMiura** [comment] 2020-02-27 22:44
in hkDME print every model name that wasn't picked up by an if statement. the model might have been renamed from `models/player` to something else.

**Comment by tamas0313** [comment] 2020-02-28 13:06
> you don't have to do that...interpret it for yourself as "if string contains"... "models/player" inlcudes all your if statements.

can u help me? can you show me ur code?

**Comment by steel4me** [comment] 2020-02-28 17:18
> in hkDME print every model name that wasn't picked up by an if statement. the model might have been renamed from `models/player` to something else.

O.K., i try.

> can u help me? can you show me ur code?
At the moment i have no solution sorry, I only said that this statement -> `if (std::strstr(info.model->name, "models/player"))` matches all your other statements, cause, when info.model->name contains "models/player" the if result will already be true!

**Comment by tamas0313** [comment] 2020-02-28 17:30
ohhhh thank you i understand

**Comment by ZerGo0** [comment] 2020-02-28 20:43
The models with patches are probably causing this issue. I tried to debug it, but I couldn't get anything useful out of my test. I pretty much logged all models in a file, but the missing model wasn't there. 

Might sound retarded, but it doesn't seem like drawModelExecute picks them up. ^^

**Comment by danielkrupinski** [comment] 2020-02-28 20:53
@ZerGo0 Thanks for the info. I think I've found the cause - we abort chams drawing if material has been overriten (to fix glow not working with chams enabled) https://github.com/danielkrupinski/Osiris/blob/8af4c1366f61e7b3c300a38598ebe17aa9583515/Osiris/Hacks/Chams.cpp#L63 and because patches override player material (just like weapon skins do) chams aren't working.

**Comment by steel4me** [comment] 2020-02-29 11:03
> The models with patches are probably causing this issue. ~I tried to debug it, but I couldn't get anything useful out of my test. I pretty much logged all models in a file, but the missing model wasn't there.~
> 
> ~Might sound retarded, but it doesn't seem like drawModelExecute picks them up. ^^~
> 
> Nvm, it actually picks them up, not really sure why it doesn't apply the chams tbh.

yesterday i gave up too, after logging everything i was able. but i have not much knowledgeas you have.

> @ZerGo0 Thanks for the info. I think I've found the cause - we abort chams drawing if material has been overridden (to fix glow not working with chams enabled)
> 
> https://github.com/danielkrupinski/Osiris/blob/8af4c1366f61e7b3c300a38598ebe17aa9583515/Osiris/Hacks/Chams.cpp#L63
> 
> and because patches override player material (just like weapon skins do) chams aren't working.

That makes sense now. Thank you for explaining.

**Comment by danielkrupinski** [comment] 2020-02-29 12:11
Probably fixed in 6c856033c49a4608ad447762f86890ddcc5e21d7

**Comment by ZerGo0** [comment] 2020-02-29 12:24
> Probably fixed in [6c85603](https://github.com/danielkrupinski/Osiris/commit/6c856033c49a4608ad447762f86890ddcc5e21d7)

Pretty sure that you also have to change this? 
https://github.com/danielkrupinski/Osiris/blob/6c856033c49a4608ad447762f86890ddcc5e21d7/Osiris/Hooks.cpp#L207

**Comment by steel4me** [comment] 2020-02-29 12:30
> > Probably fixed in [6c85603](https://github.com/danielkrupinski/Osiris/commit/6c856033c49a4608ad447762f86890ddcc5e21d7)
> 
> Pretty sure that you also have to change this?
> https://github.com/danielkrupinski/Osiris/blob/6c856033c49a4608ad447762f86890ddcc5e21d7/Osiris/Hooks.cpp#L207

i think yes, what you dont see on my screens, i have glow activated on weapons, maybe thats why no others got same problem, cause they don't use glow.

**Closed** 2020-02-29 14:51 UTC
Labels: bug, game update
