### ISSUE TITLE
Fix the rcs(please help)

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1268] opened 2020-03-16 14:47 UTC
hello Daniel, could you please fix the RCS and change it so that it's more of a pitch, yaw and standalone RCS
the RCS in the cheat is very very bad, it doesn't even control recoil, it kinda just doesn't work with the aimbot.
I don't know how to code, so i need your help guys.

**Comment by HowToMakeFaceitAB** [comment] 2020-03-16 14:48
oh and btw, if the aimbot doesn't kill said target within the first few shots, it will never kill it after unless it does because of spread

**Comment by Finndramere** [comment] 2020-03-16 15:40
#769

**Comment by xAkiraMiura** [comment] 2020-03-16 17:23
> 
> 
> #769

that is closed.

i thought the aimbot never hit because it doesn't wait for you to completely stop, this does make more sense because it doesn't hit even with slow walk.

**Comment by vsnrytune** [comment] 2020-03-18 00:15
> > #769
> 
> that is closed.
> 
> i thought the aimbot never hit because it doesn't wait for you to completely stop, this does make more sense because it doesn't hit even with slow walk.

even tho it's closed, i've been using it for a month and it works perfectly fine, no bans either

**Comment by xAkiraMiura** [comment] 2020-03-18 07:18
> 
> 
> > > #769
> > 
> > 
> > that is closed.
> > i thought the aimbot never hit because it doesn't wait for you to completely stop, this does make more sense because it doesn't hit even with slow walk.
> 
> even tho it's closed, i've been using it for a month and it works perfectly fine, no bans either

it uses an old version of Osiris that would crash after the 3/2/2020 update? unless you merged it i dont know how you could have got it to work.

**Comment by steel4me** [comment] 2020-03-18 15:17
i have better and actual version with rcs (watch my cherry-pulls and cherry-pulls-merge branch) but i discontinued committing atm cause something triggered VAC (surely not the RCS). At the moment i can count 5 VAC banned accounts since 16.02.20 more and more accounts getting delay banned now. At 13.02.20 i have merged engine prediction from master to my branch.

@xAkiraMiura please stop answering that osiris is UD. I dont use VAC-bypass and i will never use it. My own injector is used since years without any detections. I only used highly modificated osiris over a long time without problems. And no, i dont use junk code.

@danielkrupinski, please can you double check engine prediction and commits after 13.02, something is strange.

**Comment by m0nsterJ** [comment] 2020-03-18 18:22
I have never been VAC banned while using Osiris and I'm using no modifications on Osiris just the regular one, I'm using gerass's Injector,never had any issues with either of them

**Comment by xAkiraMiura** [comment] 2020-03-18 19:54
@steel4me are you sure you don't have osiris on your C:/ drive? Any cheat on the system partition will get detected by VAC through the USN journel.
I've never gotten VAC or untrusted from using Osiris so the problem is on your machine.

**Comment by HowToMakeFaceitAB** [comment] 2020-03-19 08:43
> @steel4me are you sure you don't have osiris on your C:/ drive? Any cheat on the system partition will get detected by VAC through the USN journel.
> I've never gotten VAC or untrusted from using Osiris so the problem is on your machine.

how do you merge multiple pull requests into osiris

**Comment by steel4me** [comment] 2020-03-19 09:39
@xAkiraMiura please, i have a virtual drive d:\meme.vhdx this drive is formatted as fat32 and mounted with drive letter x:, from there i start my loader / injector. The dll is streamed directly to memory from https source of my nginx in local network. 

Thats why the dll is not stored / accessible on any hard disk. From there i work with manual map and erase pe header. I use this method since many years and i had no detections, never! Detections now happened since feb 2020. Strangly, bans er delayed with over 6 weeks till now.
I know some accounts that are already flagged and will be banned till mid of april.

You can ignore what i say. It's just a clue, sometimes, you shouldn't ignore everything and belive others. How can you know that osisirs sigs or parts of it are not already known on VAC modules? Exactly, also you know which modules are loaded/streamed? It is also not possible that there are new modules? Yes sir, it is not detected. You cant say this ;) It is just wrong to say yes or no.

> I have never been VAC banned while using Osiris and I'm using no modifications on Osiris just the regular one, I'm using gerasss' Injector.
> Edit: And I'm not using the VAC Bypass either
@m0nsterJ i use osiris ~12 months, detections happened since 01.02.20, that means 9 month without any ban. **Fact**: Detection was somewhere near mid of feb and bans happened 6 weeks later.

But it's okay, there is no point in discussing this topic anymore if everyone always knows everything better and ignores all the information and signals. I wish everyone the best.

**Comment by steel4me** [comment] 2020-03-19 22:36
yyy, thats it. the USN *journel*
just keep doing akira ;)

**Comment by m0nsterJ** [comment] 2020-03-20 07:55
@steel4me Osiris is undetected right now, there are no VAC bans related to the cheat. If you're using an injector thats using LoadLibrary then you'll get Untrusted/VAC banned. I've been using Osiris for so long and I've never banned using Osiris so stop spreading fake information,saying the cheat is detected.

**Comment by xAkiraMiura** [comment] 2020-03-20 09:24
> 
> 
> yyy, thats it. the USN __**journel**__
> just keep doing akira ;)

sounds more like a grudge than you know what your talking about

> @steel4me Osiris is undetected right now, there are no VAC bans related to the cheat. If you're using an injector thats using LoadLibrary then you'll get Untrusted/VAC banned. I've been using Osiris for so long and I've never been banned using Osiris so stop spreading fake information,saying the cheat is detected.

my injector uses LoadLibrary and immediately exits and it has never been caught, maybe your loader stays open for too long after injecting? (grasping at straws for an explaination, might just be the injector you use causing a red flag)

**Comment by steel4me** [comment] 2020-03-20 09:49
> @steel4me Osiris is undetected right now, there are no VAC bans related to the cheat. If you're using an injector thats using LoadLibrary then you'll get Untrusted/VAC banned. I've been using Osiris for so long and I've never been banned using Osiris so stop spreading fake information,saying the cheat is detected.

I deleted my old message that was very long cause it makes no sense to discuss anything with people that are registered since 3 days on github an spread wrong informations that osiris is undected or detected. I always said, no one of us can say its detected or undetected. Cause you simply don't know if signatures are already well known on vac modules. Some vac modules are streamed directly after opening csgo or connecting servers, others are streamed randomly.

Also do you have any clue about the fact how valve bans your account? I just inform everyone here that my detections happened somewhere near middle of februar. my account was banned in the middle of april. that means there was a delay between detection and ban. Actual i can confirm that this delay is round about 6 weeks. Also i have 10 test accounts injected with diffrent dll's, i also know that account 5/5 will get banned near 14.04.20.

Just think what you want. I have a virtual drive mounted as drive x: formatted with fat32. My .dll's are streamed from nginx over https directly to memory and then manual mapped with erase pe header over my own loader on this drive x:. I use my own loader / injector since 5 years without detections (excpetion VMT hook detection in 2017), I used highly modificated osiris 12 month now, that means 9 months without problems.

This is my last post now. I only tried to inform you about some facts but you just igrnore everything. Stay save ;)

**Comment by xAkiraMiura** [comment] 2020-03-20 09:55
safe*
ok.

**Comment by steel4me** [comment] 2020-03-20 10:03
> safe*
> ok.

do you actually have something productive to contribute instead of constantly knowing everything better and correcting others? please change your behavior, that's not nice

**Comment by m0nsterJ** [comment] 2020-03-20 11:52
@steel4me hm very weird...
I have around 7 non primes, and I used Osiris on all of them,nothing else,and I did not receive a VAC ban,so I can say that its undetected.
I dont know what shit injector you're using to get banned lol
Also, it doesnt matter when I created that github account and you are obviously the one spreading wrong informations.

**Comment by steel4me** [comment] 2020-03-20 12:19
> @steel4me hm very weird...
> I have around 7 non primes, and I used Osiris on all of them,nothing else,and I did not receive a VAC ban,so its safe to say that its undetected.
> I dont know what shit injector you're using to get banned lol
> Also, it doesnt matter when I created that github account and you are obviously the one spreading wrong informations.

Where do i spread wrong infomations? Seems you did not read everything correctly. I only inform what happened. Show me some injector on github that streams a dll from some http(s) source to memory. It is my own and yes, ok, you can call it "shit injector". My good old internal with less functionsn then osiris doesnt trigger any vac with same injector. Believe it or not.

**One example**: i only want to say. That it is **possible**, that a vac module already detected something while you used osiris in february, but your vac ban will happen somewhere this or next month in cause of some **possible** feature detection.

this is almost worse here than in any cheater forums, the linguistic tone is broken .. lol, shit!

**Closed** 2020-03-21 09:19 UTC
