### ISSUE TITLE
[2Questionsforthebestcoderever]

### ISSUE THREAD

**Issue by YallAintthehomies** [danielkrupinski/Osiris#1879] opened 2020-07-12 08:46 UTC
@danielkrupinski Would you ever do Rage (Spin bot for example) in cs?
also would you be willing to make hacks in other video games?
The first question is kinda serious I think you could make a good Spinbot
The second question is not very serious, don't get me wrong I would love to see maybe EAC bypass or MW aimlock, but you might already have enough on your hands

**Comment by Cyk-Fad** [comment] 2020-07-12 10:12
no,Osiris is a legit hack and if you want Spin bot, You can find it in pulls

**Comment by notgoodusename** [comment] 2020-07-12 19:15
> no,Osiris is a legit hack and if you want Spin bot, You can find it in pulls

or he can make one for himself since all the pulls about desync aa arent correct, including mine

**Comment by Yodawg-Osirisuser** [comment] 2020-07-12 23:42
Osiris's anti aim is already pretty much a spinbot. If you don't believe me, inject Osiris only turn on anti aim and put pitch to 89. Go into a comp match download the replay and watch it You are literally looking at the ground and it looks like you are using any old spinbot. The issue is Osiris's aimbot doesn't work as well as OTC or Skeet or whatever they are called.

**Comment by YallAintthehomies** [comment] 2020-07-13 03:23
> no,Osiris is a legit hack and if you want Spin bot, You can find it in pulls

I'm new to Github and also to coding (I just started learning C++ yesterday) so how would I add stuff from the pulls into the hack?

**Comment by Yodawg-Osirisuser** [comment] 2020-07-16 00:45
PLease close this

**Closed** 2020-07-16 00:48 UTC
