### ISSUE TITLE
Finally getting ban

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#1727] opened 2020-06-10 16:12 UTC
Recently login my old CS:GO account and this happen

**Non Prime**
**Sergeant Major Rank 18** (almost prime)

https://steamcommunity.com/profiles/76561199002293173

I used Osiris since **Private Rank 2**.

i don't know when this happen

**Comment by dapaster** [comment] 2020-06-11 00:05
lol

**Comment by xXTOO-HARDXx** [comment] 2020-06-11 06:13
> This is not an Osiris problem. Close this issue.

How can you be so sure? There's been a huge influx of bans for people using Osiris, and I don't believe it was associated with any ban wave. So, what's to blame if it's 'not Osiris'

**Comment by hyperxpro** [comment] 2020-06-11 07:00
> > This is not an Osiris problem. Close this issue.
> 
> How can you be so sure? There's been a huge influx of bans for people using Osiris, and I don't believe it was associated with any ban wave. So, what's to blame if it's 'not Osiris'

There are countless issues regarding bans. People rage, get OW and finally VAC ban.

VAC after Game Ban is very normal.

**Comment by xAkiraMiura** [comment] 2020-06-11 07:15
VAC after an OW ban is the behaviour that VACnet used to do, theres a chance that something osiris is doing is getting picked up by VACnet.

**Comment by hyperxpro** [comment] 2020-06-11 07:17
Or, VAC knows that you injected some shit. But it doesn't ban unless VAC is 100% sure it's a cheat. Once you get a game ban, it leaves no doubt that the injected shit was a cheat.

**Comment by xXTOO-HARDXx** [comment] 2020-06-11 07:30
Right, but, if that were the case, then could someone explain my bans? 

I only ever used Radar (bSpotted) and every day I used it I customised the source code to really shake up the signature, by running an automation script which automatically renames functions, variables, switches order of operations (basically turns repeating functions into for loops and vice versa + randomisation, using #define to tell the program what to do and where), and also protecting my .dll's using code mutation and other shit for "safety".

So, by those means, I can exclude anything to do with signatures because it changes so drastically. So, what is left to be the cause of my bans.. hooking? SOMEHOW one of the features... ? ... Please, have a go.

**Comment by hyperxpro** [comment] 2020-06-11 07:42
The signature shake-up is joke. Aimware changes signature on every run and still Aimware users get banned in bulk every 6-9 months or so.

If you hack and you expect *NO BAN* then good luck.

**Comment by xXTOO-HARDXx** [comment] 2020-06-11 07:50
> The signature shake-up is joke. Aimware changes signature on every run and still Aimware users get banned in bulk every 6-9 months or so.
> 
> If you hack and you expect _NO BAN_ then good luck.

I, for one, never said I expected no ban.
Two, I don't see how anything I said referencing the signature shake-up was a joke...
If Aimware's signature changes enough on every run (which you're yet to prove), I doubt that people are getting banned plainly because of the signature, especially since there's zero proof on why they're banned in waves.

**Comment by hyperxpro** [comment] 2020-06-11 07:55
Head here doggie: https://www.valvesoftware.com/fi/contact?contact-person=Gabe%20Newell

**Comment by xXTOO-HARDXx** [comment] 2020-06-11 08:04
> Head here doggie: https://www.valvesoftware.com/fi/contact?contact-person=Gabe%20Newell

Are you trolling or just being dumb? Like fr. If you're not going to continue to contribute to the conversation then don't bother talking crap.

I've kept my own cheat undetected for long enough to know how to keep myself from getting 'signature banned' lmao

**Comment by hyperxpro** [comment] 2020-06-11 08:30
If you've your own cheat, why using Osiris? hah.

**Comment by xXTOO-HARDXx** [comment] 2020-06-11 08:34
> If you've your own cheat, why using Osiris? hah.

Well, I haven't always had my own cheat, hah.

... I don't use Osiris anymore, I haven't for a while now. But while I WAS still using it (1 month ago or smth), my main was banned afterwards (about 15 days ago).

I've also had other accounts banned from Osiris, which were strictly for testing Osiris with new stuff, which were also banned, so, yeah.

**Comment by steel4me** [comment] 2020-06-13 08:30
Really funny, 3 month later and see what happened, nobody believed me, even now, everyone deny it. Anyone who is interested should read these closed issues below.

It is really simple, stop using osiris till it get fixed.
I wasted over 5 accounts with osisris and got vac, my osiris clone was highly modificated.
I use my own injector over 15 years now, never got vac.

Im still using my injector over 3 month now. No vac, no ban, nothing. Just other dll, no osiris anymore ;)

#1246
#1238
#1251
#1268
#1306

**Comment by hyperxpro** [comment] 2020-06-13 08:32
Valve can literally see the source code. What else you can expect? XD

**Comment by m0nsterJ** [comment] 2020-06-13 08:32
@steel4me Either your Injector is shit or you get game banned and VAC banned afterwards. Every single time someone reports that they received a VAC ban you have to comment and say that nobody believed you. I didn't get VAC banned a single time so stop spreading fake information. Also, we don't know what Injector this guy used. Close this Issue.

**Comment by hyperxpro** [comment] 2020-06-13 08:39
@steel4me Either get used to bans or leave hacking. It's so retarded to cry after getting banned for cheats.

**Comment by steel4me** [comment] 2020-06-13 13:31
oh i missed this useless comments.  i don't care about banned accounts. you got me wrong. i just give info. for you, the short version. i used highly modificated teamgamerfood and added lots of things over many, many years, it was no problem to stay undetected. then i decided to try osiris, change big parts, added some things and deleted whole features without vac bypass. i played over 8 month without any detection but always pulled repo. somewhere in february something triggered a vac ban. i tried to find out what it was but never found it. sure thing is. it is not the injector cause im fine since 3 month now and back to my old .dll with less features. but it is okay for me ;)

**Comment by techzin** [comment] 2020-06-24 00:14
It seems to me that it is now undetectable.

**Comment by xXTOO-HARDXx** [comment] 2020-06-24 01:26
> It seems to me that it is now undetectable.

No, it isn't 'undetectable', but the hooking is no longer detected.

This issue should be closed.

**Closed** 2020-06-24 13:28 UTC
