### ISSUE TITLE
sv_pure bypass? 

### ISSUE THREAD

**Issue by icantfindausernamelol** [danielkrupinski/Osiris#1553] opened 2020-05-08 01:01 UTC
Is there a way to implement a sv_pure bypass feature in Osiris. If yes how?

**Comment by xpossed-you** [comment] 2020-05-08 11:29
yes

**Comment by littlehurensohn** [comment] 2020-05-09 00:40
Like that: https://www.unknowncheats.me/forum/counterstrike-global-offensive/279394-dumb-sv_pure-bypass.html

**Comment by Cyk-Fad** [comment] 2020-05-09 08:33
https://www.unknowncheats.me/forum/counterstrike-global-offensive/392489-fixing-sv_pure-kicks.html

**Comment by hyperxpro** [comment] 2020-05-10 11:28
Duplicate of #1235, #1138. #687, #569, #442 and #416

**Closed** 2023-10-04 18:29 UTC
