### ISSUE TITLE
update log 

### ISSUE THREAD

**Issue by uzdiiilekk** [danielkrupinski/Osiris#2306] opened 2020-11-08 21:37 UTC
add update log please because you update osiris every week xd

**Comment by VuBrian22** [comment] 2020-11-09 00:11
~Redundant Duplicate of #2297 by the same user @uzdiiilekk 

All commits are self-explanatory. New features or reworked features are in the README. Most of the updates are optimizations. We've already solved this. There is no need for an update log if you can do a little bit of reading.

Please Close This Issue.

**Closed** 2020-11-09 06:53 UTC
