### ISSUE TITLE
Triggerbot not work now

### ISSUE THREAD

**Issue by fwb5** [danielkrupinski/Osiris#1038] opened 2020-01-30 13:05 UTC
plz update，thx

**Comment by anarbmw** [comment] 2020-01-30 13:12
close ur stupid issue, they already fixed it ==

**Comment by Bywnb** [comment] 2020-01-30 13:23
hahaha

**Comment by fwb5** [comment] 2020-01-30 13:23
> 解决了您的愚蠢问题，他们已经解决了==

no u asshole

**Comment by Asviix** [comment] 2020-01-30 13:27
#1306

**Comment by Asviix** [comment] 2020-01-30 13:28
Duplicate of #1036

**Closed** 2020-01-30 18:17 UTC
