### ISSUE TITLE
Random crashes on inject

### ISSUE THREAD

**Issue by effex1337** [danielkrupinski/Osiris#129] opened 2019-04-20 11:53 UTC
I don't know to what extent this is true but osiris randomly crashes on inject on nvidia gpus.
The reason I'm saying it is i never crashed on My Home laptop. But it randomly crashes on some of my friends' pc with nvidia gpus. P.S. i don't have any gpu.
This is just my guess but i don't think cfg is the issue.

**Comment by danielkrupinski** [comment] 2019-04-20 11:58
Do your friends' CPUs support AVX 2 instruction set?

**Comment by NexSqaud** [comment] 2019-04-21 11:47
I have a nvidia video card and the game does not crash. CPU supports AVX (not AVX2)

**Comment by NexSqaud** [comment] 2019-04-25 13:32
ok, new version is crashing on nvidia gpus

**Comment by NexSqaud** [comment] 2019-04-26 11:21
access violation when reading at 0x00002FAA

**Comment by NexSqaud** [comment] 2019-05-10 11:38
Exception thrown at 0x762A0C35 (ucrtbase.dll) in csgo.exe:
0xC0000005: Access violation reading location 0x00000018

EAX = 00000000
EDX = 00000018
EBX = 00000400
ESI = 00000000

**Comment by danielkrupinski** [comment] 2019-05-10 13:13
@NexSqaud Exception is thrown in C RunTime library, it is not caused by Osiris, probably your injector's fault. Closing.

**Closed** 2019-05-10 13:14 UTC

**Comment by NexSqaud** [comment] 2019-05-11 06:44
But i tried inflame injector now,
