### ISSUE TITLE
Can't inject Osiris 2

### ISSUE THREAD

**Issue by trashcuff** [danielkrupinski/Osiris#2350] opened 2020-11-27 17:40 UTC
I use process hacker, when i inject the newest build of the dll nothing happens

**Comment by franiodat** [comment] 2020-11-27 19:50
try csghost  or something

**Comment by franiodat** [comment] 2020-11-27 19:51
process hacker has inject func, but this is not a injector

**Comment by trashcuff** [comment] 2020-11-27 21:49
> process hacker has inject func, but this is not a injector

it has worked for me with osiris in the past tho

**Comment by veikkop** [comment] 2020-11-30 10:31
csgo has started to block processhacker so it doesnt work

**Comment by trashcuff** [comment] 2020-11-30 14:56
yeah seems like it, i am using sazinjector now

**Comment by caiocinel** [comment] 2020-11-30 17:53
If your problem has been resolved close the issue, it helps to keep things in order.

**Comment by debooga** [comment] 2020-12-06 22:14
**For anyone reading this issue:** This may be caused by load library injectors, just use a manual mapping one.

**Closed** 2021-03-16 14:15 UTC
