### ISSUE TITLE
add lua codes

### ISSUE THREAD

**Issue by Shuvi-Moro** [danielkrupinski/Osiris#1561] opened 2020-05-09 11:40 UTC
what about to add lua codes?
here is the link https://github.com/TXIuTnVsbA/Osiris_Edit
I think this will be a very correct decision

**Comment by Cyk-Fad** [comment] 2020-05-09 11:57
no

**Comment by BellBush** [comment] 2020-05-09 17:48
That is osiris written in lua, not lua scripts as you are thinking, that is just osiris in another progam language. If you took the time to translate the chinks writing you would understand all he is doing is rewrting osiris in lua.

**Comment by xpossed-you** [comment] 2020-05-10 07:13
no

**Comment by hyperxpro** [comment] 2020-05-10 11:26
Duplicate of #268, #837, #1270

**Comment by NekoRem** [comment] 2020-05-10 13:54
i modified this code and made it my own and works perfectly with the latest Osiris build, but as it is only myself using this i believe it is quite useless...

**Closed** 2020-05-11 17:38 UTC
