### ISSUE TITLE
Pure server: client file doesnt match server (error)

### ISSUE THREAD

**Issue by Rcsette** [danielkrupinski/Osiris#1533] opened 2020-05-05 02:23 UTC
''Pure server: client file doesnt match server.
https://support.steampowered.com/kb_article.php?ref=8285-YOAZ-6049"

I get kicked by the server after minutes playing with Osiris and get thsi message. Without Osiris nothing happens.

Any Solution?

Edit: It is happening to anyone, not only using Osiris.

**Comment by 3Ld4D** [comment] 2020-05-05 02:24
it happens to legits too

**Comment by Rcsette** [comment] 2020-05-05 02:25
But I only gets it with Osiris. Noticed that it is happening after the today's update on CS:Go.

**Comment by 3Ld4D** [comment] 2020-05-05 02:26
they tried to fix the sv_pure bypass and they fucked up badly

**Comment by OBO-1** [comment] 2020-05-05 04:43
i think its because of skin changer.

**Comment by rypx** [comment] 2020-05-05 08:18
Without injecting Osiris, csgo perfectly fine, playing 3 deathmatch & 1 mm.

**Comment by HackerGeo-sp1ne** [comment] 2020-05-05 10:33
![image](https://user-images.githubusercontent.com/42976769/81057369-f56d1880-8ed4-11ea-82f7-5f8b5ca5ff88.png)

**Comment by twangsriprasoet** [comment] 2020-05-05 12:07
here's the fix
https://www.youtube.com/watch?v=kow7r58HMY0

**Comment by HowToMakeFaceitAB** [comment] 2020-05-05 12:23
go to the csgo directory and go into the csgo folder, you should find materials and models, rename them

**Comment by rypx** [comment] 2020-05-05 12:34
> go to the csgo directory and go into the csgo folder, you should find materials and models, rename them



> here's the fix
> https://www.youtube.com/watch?v=kow7r58HMY0

worked without osiris injected.

tried using external nor other internal cheats, it's oddly worked without any problem.
_ikr my english sucks._

**Comment by ChickenNerd** [comment] 2020-05-05 13:50
Umm. the sv_pure update is the cause for this i think. Here's what Valve said: `sv_pure servers will now kick clients that have loaded asset files into game memory from files not present on game server filesystem.`
Are these files normally in the CS folder?
`D:\Gry Steam\steamapps\common\Counter-Strike Global Offensive\csgo\materials\chamsAnimated.vmt`
`D:\Gry Steam\steamapps\common\Counter-Strike Global Offensive\csgo\materials\chamsFlat.vmt`
`D:\Gry Steam\steamapps\common\Counter-Strike Global Offensive\csgo\materials\chamsNormal.vmt`
`D:\Gry Steam\steamapps\common\Counter-Strike Global Offensive\csgo\materials\glowOverlay.vmt`

Maybe Osiris injects those files into the games memory, so it kicks you. I think those files are used in osiris chams. Here's the code: ```
Chams::Chams() noexcept
{
    std::ofstream{ "csgo/materials/chamsNormal.vmt" } <<
        "VertexLitGeneric { }";

    std::ofstream{ "csgo/materials/chamsFlat.vmt" } <<
        "UnlitGeneric { }";

    std::ofstream{ "csgo/materials/chamsAnimated.vmt" } <<
        "VertexLitGeneric { $envmap editor/cube_vertigo $envmapcontrast 1 $envmaptint \"[.7 .7 .7]\" $basetexture dev/zone_warning proxies { texturescroll { texturescrollvar $basetexturetransform texturescrollrate 0.6 texturescrollangle 90 } } }";
   
    std::ofstream("csgo/materials/glowOverlay.vmt") <<
        "VertexLitGeneric { $additive 1 $envmap models/effects/cube_white $envmaptint \"[1 0 0]\" $envmapfresnel 1 $envmapfresnelminmaxexp \"[0 1 2]\" $alpha 0.8 }";

    normal = interfaces->materialSystem->findMaterial("chamsNormal");
    normal->incrementReferenceCount();
    flat = interfaces->materialSystem->findMaterial("chamsFlat");
    flat->incrementReferenceCount();
    animated = interfaces->materialSystem->findMaterial("chamsAnimated");
    animated->incrementReferenceCount();
```

**Comment by wirebruh** [comment] 2020-05-05 14:03
yeah that might be a problem, just update your osiris paste

**Comment by Or3nges** [comment] 2020-05-05 14:11
Waiting for Daniel to update it, or is it already fixed on the latest version of Osiris?

**Comment by wirebruh** [comment] 2020-05-05 14:13
It is in Osiris. I think this kick is caused by the cheat creating .vmt files in csgo directory.

**Comment by wirebruh** [comment] 2020-05-05 14:13
I reinstalled my game, didn't inject and played legit, didn't get kicked. Injected and got kicked after a few minutes (2-7 minutes).

**Comment by wirebruh** [comment] 2020-05-05 14:14
If you use your own materials you have to update them aswell.

**Comment by danielkrupinski** [comment] 2020-05-05 14:49
The cheat does not create material files anymore, it creates them directly from memory.

**Comment by wirebruh** [comment] 2020-05-05 14:53
> The cheat does not create material files anymore, it creates them directly from memory.

I know, but some people didn't update the cheat or/and are using their own materials.

**Comment by ChickenNerd** [comment] 2020-05-05 15:41
Yeah, just update Osiris if you have this problem. You can close this thread

**Comment by HackerGeo-sp1ne** [comment] 2020-05-05 15:46
ok but how to solve this? i don't not understand

**Comment by 3Ld4D** [comment] 2020-05-05 15:58
i don't see cham materials being the issue bc i just went 2 wingman games

**Comment by wirebruh** [comment] 2020-05-05 16:01
Just update the cheat and delete .vmt files that Osiris is no longer using from /csgo/materials.

**Comment by 3Ld4D** [comment] 2020-05-05 16:14
> Just update the cheat and delete .vmt files that Osiris is no longer using from /csgo/materials.

it has nothing to do with this error, like i said i just went 2 wingman games and i didn't get kicked single time.

**Comment by HackerGeo-sp1ne** [comment] 2020-05-05 16:22
Now i get crash https://github.com/danielkrupinski/Osiris/issues/1539

**Comment by wirebruh** [comment] 2020-05-05 18:05
> > Just update the cheat and delete .vmt files that Osiris is no longer using from /csgo/materials.
> 
> it has nothing to do with this error, like i said i just went 2 wingman games and i didn't get kicked single time.

Deleting these files helped around 4 people already.

**Comment by wirebruh** [comment] 2020-05-05 18:06
My friend played for an hour and didn't get kicked. He got kicked later so it might happen to you too.

**Comment by 3Ld4D** [comment] 2020-05-05 19:24
> My friend played for an hour and didn't get kicked. He got kicked later so it might happen to you too.

i played comp for 4h when update came out and wingman today so i don't think it's that

**Closed** 2020-05-06 00:20 UTC
