### ISSUE TITLE
Is Osiris really detected?

### ISSUE THREAD

**Issue by LOG1CC** [danielkrupinski/Osiris#1708] opened 2020-06-07 12:22 UTC
A lot of people are saying there has been a vac wave and Osiris got detected. However, I didn't get banned even tho I was using it every day for a month straight with the only exception when it wasn't updated for 2 or more days. Personally I don't think it got detected, also a lot of people saying they got a VAC actually got an overwatch. I guess it could be delayed bans from other cheats.

**Comment by techzin** [comment] 2020-06-07 14:58
Hello, in the tests done by me, I realized that Osiris was really detected, but the people who used VAC Bypass were not very affected by it, and not everyone received a ban I tested on some free accounts, and only 2 received VAC bans.

**Comment by TheFantasticLoki** [comment] 2020-06-07 14:59
I can confirm at least 1 VAC ban. no OW bans tho.

**Comment by techzin** [comment] 2020-06-07 14:59
But I believe that with these updates that danielkrupinski
are doing, this must be corrected.

**Comment by techzin** [comment] 2020-06-07 15:00
I will be doing more tests with Osiris soon, to make sure it has been fixed.

**Comment by TheFantasticLoki** [comment] 2020-06-07 15:00
> 
> 
> I can confirm at least 1 VAC ban. no OW bans tho.

Tho I never used VAC Bypass as I had not heard of it till now and most in the past have not worked.

**Comment by TheFantasticLoki** [comment] 2020-06-07 15:44
yea it was 100% detected cause now every account that I ever used osiris on has been VAC banned no OW ban.

**Comment by TheFantasticLoki** [comment] 2020-06-07 15:46
that must have been what happened to my main account a few weeks ago is an old version of osiris was detected. Unfortunate.

**Comment by LOG1CC** [comment] 2020-06-07 16:20
Oh really? I suppose vac ban bypass will be getting patched soon.

**Comment by techzin** [comment] 2020-06-07 16:32
Well, Osiris, as everyone knows, is an open source Free Cheat, with no blame for bans, since it is for educational purposes, so it is common to have some bans in its trajectory.
I see it that way.

**Comment by ChickenNerd** [comment] 2020-06-07 19:18
got ow, turned into vac a few hours later

**Comment by Floraly** [comment] 2020-06-07 20:13
VAC and Game Bans are delayed. If you get VAC Banned today keep in mind the detection could happen days or weeks in the past!

**Comment by hastydev** [comment] 2020-06-07 21:14
cheated for 1 game on 2 accounts - both no vac/ow yet
cheated for 30 games on an account - was overwatch, turned into vac 1 hour later. probably vacnet I guess

**Comment by Robstersgaming** [comment] 2020-06-07 21:32
Does the creator of osiris update the cheat to avoid vac bans?? or is it just a reference for other cheat makers

**Comment by TauCSGO** [comment] 2020-06-07 22:34
> cheated for 1 game on 2 accounts - both no vac/ow yet
> cheated for 30 games on an account - was overwatch, turned into vac 1 hour later. probably vacnet I guess

ban times are random but on average it takes a week to hit the system from the moment it is detected

**Comment by steel4me** [comment] 2020-06-08 06:15
> > cheated for 1 game on 2 accounts - both no vac/ow yet
> > cheated for 30 games on an account - was overwatch, turned into vac 1 hour later. probably vacnet I guess
> 
> ban times are random but on average it takes a week to hit the system from the moment it is detected

no, it can take up to 12 weeks with delay ban. something was detected in the past (it was not the injector), it took me 5 accounts ;) playing with same injector since februar and other dll without any problems or detections. never used vac bypass

**Comment by littlehurensohn** [comment] 2020-06-08 08:03
Yes, detected hooking.

**Comment by aljawary** [comment] 2020-06-08 08:39
> Yes, detected hooking. //Remake hooking and everything be okay.

with minhook?

**Comment by xXTOO-HARDXx** [comment] 2020-06-08 09:27
> Yes, detected hooking. //Remake hooking and everything be okay.

how do you know for sure that it's the vmt's that are detected? or are you just speculating..

**Comment by steel4me** [comment] 2020-06-08 09:28
> Yes, detected hooking. //Remake hooking and everything be okay.
When yes, daniel should change it, maybe he already has. I don't know, i didnt watched commits since months.

**Comment by XDarkTitan** [comment] 2020-06-08 10:53
Well guys I accidentally injected a detected version what will happen ?

**Comment by Megalounge** [comment] 2020-06-08 10:56
> Well guys I accidentally injected a detected version what will happen ?

nothing will happen if you didn't go into a VAC secured server

**Comment by XDarkTitan** [comment] 2020-06-08 10:57
I did play some games tho

**Comment by XDarkTitan** [comment] 2020-06-08 10:58
my 1 acc got overwatched but the other haven't received a ban yet.
what is the difference with Overwatch and VAC

**Comment by Megalounge** [comment] 2020-06-08 10:59
> I did play some games tho

then you will most likely fuck up, i guess you have to wish urself luck

**Comment by XDarkTitan** [comment] 2020-06-08 11:02
is the previous osiris got detected because I just got overwatched instead of VAC

**Comment by steel4me** [comment] 2020-06-08 11:09
> is the previous osiris got detected because I just got overwatched instead of VAC
> 
> or is it delayed

You should not cheat if you dont know the differences between overwatch and vac ban.

Please read this for overwatch -> https://support.steampowered.com/kb_article.php?s=923d0682fcb496de89929073694a2fe7&ref=7562-IPJN-1009

Please read this fot vac -> https://support.steampowered.com/kb_article.php?ref=7849-RADZ-6869

**Comment by rypx** [comment] 2020-06-08 12:42
![image](https://user-images.githubusercontent.com/46881089/84031596-281c9c00-a9c0-11ea-9d11-fc42d3b7d0bb.png)
game ban, ow i guess

**Comment by XDarkTitan** [comment] 2020-06-08 13:39
so OW ban means someone watched your gameplay?

**Comment by xXTOO-HARDXx** [comment] 2020-06-08 14:22
Can anyone please confirm what in Osiris has been detected? Is it actually the hooking? Or a certain feature (doubt it)? Or what.. Thanks.

**Comment by littlehurensohn** [comment] 2020-06-08 16:34
@xXTOO-HARDXx Features? wtf. Hooking is detected, just remake it and get profit.

**Comment by zxsleebu** [comment] 2020-06-08 17:18
i can confirm 1 vac ban. account: abbitsm9pena94039001

**Comment by AntonDoil** [comment] 2020-06-08 20:35
I tested daniel's newest osiris build. 

https://steamcommunity.com/profiles/76561199037938013/

Btw: I used vac bypass.

**Comment by xXTOO-HARDXx** [comment] 2020-06-08 21:27
> @xXTOO-HARDXx Features? wtf. Hooking is detected, just remake it and get profit.

It wasn't very obvious to anyone that hooking is the issue, you mong. I asked the guy to confirm it and he never did. And .. Why are you saying "FeATuReS??[???¿" Like it couldn't very well be the issue? "Wtf" lol

**Comment by AntonDoil** [comment] 2020-06-09 08:01
> > @xXTOO-HARDXx Features? wtf. Hooking is detected, just remake it and get profit.
> 
> It wasn't very obvious to anyone that hooking is the issue, you mong. I asked the guy to confirm it and he never did. And .. Why are you saying "FeATuReS??[???¿" Like it couldn't very well be the issue? "Wtf" lol
> 
> Thanks for confirming, I guess

"Is it actually the hooking? Or a certain feature (doubt it)?" stupid dumbass

**Comment by xXTOO-HARDXx** [comment] 2020-06-09 08:41
> > > @xXTOO-HARDXx Features? wtf. Hooking is detected, just remake it and get profit.
> > 
> > 
> > It wasn't very obvious to anyone that hooking is the issue, you mong. I asked the guy to confirm it and he never did. And .. Why are you saying "FeATuReS??[???¿" Like it couldn't very well be the issue? "Wtf" lol
> > Thanks for confirming, I guess
> 
> "Is it actually the hooking? Or a certain feature (doubt it)?" stupid dumbass

are you just mad that I corrected you over on your other post? or are you having a really bad day...

Please explain what the fuck anyone said or did that alluded to the hooking being detected, PLEASE, be my guest... explain to someone who has been coding CSGO cheats for 5+ years how it was so blatantly obvious that it was the hooking 🤔🤔🤔🤔🤔🤔🤔 

You're an actual clown unless you got some real good explanation as to why you said "stupid dumbass", dumbass.

**Comment by realstyla23** [comment] 2020-06-09 09:24
no ban yet... used it on three accounts.. some even rage.. 

no vac bypass used either.. just had some modification in the code

**Comment by xXTOO-HARDXx** [comment] 2020-06-09 11:59
> no ban yet... used it on three accounts.. some even rage..
> 
> no vac bypass used either.. just had some modification in the code

Interesting, maybe it isn't the hooking after all..

**Comment by realstyla23** [comment] 2020-06-09 12:48
i should add.. that i used daniels Injector and osiris for about two months.. matchmaking only

**Comment by steel4me** [comment] 2020-06-13 08:31
Really funny, 3 month later and see what happened, nobody believed me, even now, everyone deny it. Anyone who is interested should read these closed issues below.

It is really simple, stop using osiris till it get fixed.
I wasted over 5 accounts with osisris and got vac, my osiris clone was highly modificated.
I use my own injector over 15 years now, never got vac.

Im still using my injector over 3 month now. No vac, no ban, nothing. Just other dll, no osiris anymore ;)

#1246
#1238
#1251
#1268
#1306

**Comment by techzin** [comment] 2020-06-24 18:40
Close This Issue.

**Closed** 2020-07-09 12:30 UTC
